---
 - name: ModulC
   hosts: servers
   become: true
   vars_files:
         - privvars.yml
   tasks:
   - name: list update deb
     apt: update_cache=yes
     when: ansible_distribution == 'Debian'
   - name: list update cen
     yum: update_cache=yes
     when: ansible_distribution == 'CentOS'
   - name: install deb
     apt: pkg={{ item }}
     with_items:
         - docker
         - docker-compose
         - git
         - curl
         - lynx
         - firewalld
         - vim              
         - mc
     when: ansible_distribution == 'Debian'
   - name: install cent
     yum: pkg={{ item }}
     with_items:
         - docker
         - curl
         - git
         - python-pip
         - firewalld
         - vim
         - lynx
         - mc
     when: ansible_distribution == 'CentOS'
   - name: install docker-composer cent
     pip: name=docker-compose
     when: ansible_distribution == 'CentOS'
   - name: git
     git:
         repo: https://github.com/andgabs/skill_hmao
         dest: /skillcloud-nginx
         clone: yes
   - name: firewalld en
     systemd:
         name: firewalld
         state: started
   - name: firewall port
     firewalld:
         port: "{{ item }}"
         permanent: true
         immediate: true
         state: enabled
     with_items:
         - 80/tcp
         - 8080/tcp
         - 1022/tcp
         - 1022/udp
   - name: change port
     lineinfile:
         path: /etc/ssh/sshd_config
         regexp: '^#?Port!'
         line: 'Port 1022'
         state: present
   - name: publick key
     lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
   - name: Restart Firewalld
     service:
        name: firewalld
        state: restarted
   - name: users
     user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        state: present
        shell: /bin/bash
        createhome: yes
     with_items:
        - '{{users}}'
   - name: create directories docker
     file:
        path: "{{ item }}"
        state: directory
     with_items:
        - /skillcloud-nginx/balance
        - /skillcloud-nginx/site
   - name: mv
     command: mv /skillcloud-nginx/Dockerfile-balance /skillcloud-nginx/balance/Dockerfile
     wait_for:
        timeout: 10
   - name: mv
     command: mv /skillcloud-nginx/Dockerfile-site /skillcloud-nginx/site/Dockerfile
     wait_for:
        timeout: 10
   - name: mv
     command: mv /skillcloud-nginx/nginx.conf /skillcloud-nginx/balance/nginx.conf
     wait_for:
        timeout: 10
   - name: mv
     command: mv /skillcloud-nginx/index.html /skillcloud-nginx/site/index.html
     wait_for:
        timeout: 10
   - name: docker balance
     command: docker build -t /skillcloud-nginx/balance/ -t balance:balance
     wait_for:
        timeout: 120
   - name: docker site
     command: docker build -t /skillcloud-nginx/site/ -t site:site
     wait_for:
        timeout: 120
   - name: docker-compose
     command: docker-compose build
     wait_for:
        timeout: 20
   - name: docker-compose up
     command: docker-compose up
     wait_for:
        timeout: 20
   - name: Restart SSH service
     systemd:
        name: ssh
        state: restarted
     wait_for:
        timeout: 10
